//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace li4_backend.Models
{
    using System;
    using System.Collections.Generic;
    public partial class Escala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escala()
        {
            this.Estatisticas = new HashSet<Estatistica>();
        }
    
        public int id_escala { get; set; }
        public int perigo { get; set; }
        public int confianca { get; set; }
        public int saude { get; set; }
        public int autonomia { get; set; }
        public int terceiros { get; set; }
        public Nullable<int> fome { get; set; }
        public string esforco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estatistica> Estatisticas { get; set; }
    }
}
