//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace li4_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public System.DateTime data { get; set; }
        public int utilizador { get; set; }
        public int gravidade { get; set; }
        public string tipo { get; set; }
        public byte[] foto { get; set; }
        public string resumo_textual { get; set; }
        public string localizacao_latitude { get; set; }
        public string localizacao_longitude { get; set; }
    
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
