//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace li4_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class li4_back_end_entities : DbContext
    {
        public li4_back_end_entities()
            : base("name=li4_back_end_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Escala> Escalas { get; set; }
        public virtual DbSet<Estatistica> Estatisticas { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<LocalInteresse> LocalInteresses { get; set; }
        public virtual DbSet<Localizacao> Localizacaos { get; set; }
        public virtual DbSet<Refugiado> Refugiadoes { get; set; }
        public virtual DbSet<RegistoCampo> RegistoCampoes { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
    }
}
