//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace li4_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalInteresse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalInteresse()
        {
            this.Utilizadors = new HashSet<Utilizador>();
            this.RegistoCampoes = new HashSet<RegistoCampo>();
        }
    
        public int id_local_interesse { get; set; }
        public System.DateTime data_registo { get; set; }
        public System.DateTime data_intervencao { get; set; }
        public string inf_adicional { get; set; }
        public Nullable<int> numero_voluntarios { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizador> Utilizadors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistoCampo> RegistoCampoes { get; set; }
    }
}
