//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace li4_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugiado
    {
        public int id_refugiado { get; set; }
        public string nome { get; set; }
        public int utilizador { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string local_registo_latitude { get; set; }
        public byte[] foto { get; set; }
        public string info_adicional { get; set; }
        public System.DateTime data_registo { get; set; }
        public string genero { get; set; }
        public byte paradeiro_conhecido { get; set; }
        public byte[] msg_voz { get; set; }
        public string local_registo_longitude { get; set; }
        public string localizacao_actual_latitude { get; set; }
        public string localizacao_actual_longitude { get; set; }
    
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
